project_id = "hdqwngiztikxpwttdecz"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://lovable.app"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false
enable_confirmations = false

[db]
port = 54322

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"

[edge_runtime]
enabled = true
port = 54325

[functions.process-donation]
verify_jwt = false

[functions.create-creator-subscription]
verify_jwt = true

[functions.rupantorpay-webhook]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.request-withdrawal]
verify_jwt = true