// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdqwngiztikxpwttdecz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkcXduZ2l6dGlreHB3dHRkZWN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMjYzNDUsImV4cCI6MjA3MTcwMjM0NX0.lzzCEng2T0LctDqhUtx61Nz4jmr412lBupqcUgOUXzM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});